name: Qt C++ CI

on:
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2' # Specify the Qt version you need

    - name: Find and Build all Qt Projects
      run: |
        find . -name '*.pro' -execdir sh -c 'mkdir -p build && cd build && qmake ../*.pro && make -j$(nproc)' \;
