name: Valgrind Analysis

on: [push, pull_request]

jobs:
  valgrind:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.7.0' # Specify the Qt version you need
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential valgrind

    - name: Add Qt to PATH
      run: echo "$HOME/Qt/5.15.2/gcc_64/bin" >> $GITHUB_PATH

    - name: Build application
      run: |
        mkdir -p build
        cd build
        qmake ../memory_test/tictactoev/tictactoe.pro
        make

    - name: Run Valgrind
      run: |
        cd build
        valgrind --leak-check=full ./tictactoe
      continue-on-error: true

